name: Publish Docker image

on:
  push:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Git gpt4free latest version
        id: ghd
        uses: proudust/gh-describe@v1
        with:
          repo: "https://github.com/xtekky/gpt4free"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Login to GitHub Container
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Get metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            mouxan/g4f
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.ghd.outputs.tag }}
            type=raw,value=latest

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            G4F_VERSION=${{ steps.ghd.outputs.tag }}
